const enum MovieDBStatusCodesEnum {
        Success = 1,
        InvalidService = 2,
        AuthenticationFailedNoPermission = 3,
        InvalidFormat = 4,
        InvalidParameters = 5,
        InvalidId = 6,
        InvalidAPIKey = 7,
        DuplicateEntry = 8,
        ServiceOffline = 9,
        SuspendedAPIKey = 10,
        InternalError = 11,
        UpdatedSuccessfully = 12,
        DeletedSuccessfully = 13,
        AuthenticationFailed = 14,
        Failed = 15,
        DeviceDenied = 16,
        SessionDenied = 17,
        ValidationFailed = 18,
        InvalidAcceptHeader = 19,
        InvalidDateRange = 20,
        EntryNotFound = 21,
        InvalidPage = 22,
        InvalidDate = 23,
        TimedOut = 24,
        OutOfLimit = 25,
        ProvideUserNameAndPassword = 26,
        TooManyAppend = 27,
        InvalidTimezone = 28,
        MustConfirmThisAction = 29,
        InvalidUsernameAndOrPassword = 30,
        AccountDisabled = 31,
        EmailNotVerified = 32,
        InvalidRequestToken = 33,
        ResourceNotFound = 34
}


export default MovieDBStatusCodesEnum;
